---
version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - env
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username
        AWS --password-stdin 852090507207.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_TAG=$(echo release-$CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c
        1-10)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push
        852090507207.dkr.ecr.us-east-1.amazonaws.com/nodejs-demo-ecr:latest
      - echo Writing image definitions file...
      - printf '[{"name":"nodejs-demo-ecr","imageUri": $REPOSITORY_URI:$IMAGE_TAG}]' > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json
